/* Automatically generated by './build/build-entry.js' */
import Wdatepicker from '../packages/Wdatepicker/index.js'
import localeIndex from './locale'
const components = [
  Wdatepicker
]

const install = function(Vue, opts = {}) {
  localeIndex.use(opts.locale)
  localeIndex.i18n(opts.i18n)

  components.forEach(function(component) {
    Vue.component(component.name, component);
  })
}

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

const version = require('../package.json').version,
locale = localeIndex.use,
i18n = localeIndex.i18n

export {
  version,
  locale,
  i18n,
  install,
  Wdatepicker,
  
}

export default {
  version,
  locale: localeIndex.use,
  i18n: localeIndex.i18n,
  install,
  Wdatepicker,
  
}
